export const sceneCopy = {
  en: {
    demo: "Interactive concept · demo data",
    live: "System ready",
    synchronized: "Synced",
    morning: "Good morning",
    today: "Today's operations",
    bookings: "Bookings",
    tasks: "Tasks",
    requests: "Requests",
    booking: "Booking #04",
    assignment: "Confirm assignment",
    selected: "Assignment selected",
    confirmed: "Assignment confirmed",
    home: "Home",
    profile: "Profile",
    overview: "Overview",
    customers: "Customers",
    workflows: "Workflows",
    reports: "Reports",
    search: "Search workspace",
    dashboard: "Operations dashboard",
    active: "Active workflows",
    open: "Open requests",
    completed: "Completed tasks",
    activity: "Recent activity",
    review: "Review request",
    reviewed: "Request approved",
    pending: "Pending review",
    done: "Complete",
    website: "STUDIO / SPACES",
    spaces: "Spaces for a better everyday.",
    websiteText: "Thoughtful spaces. Considered details. Made for living.",
    explore: "Explore spaces",
    collection: "The collection",
    living: "Living spaces",
    work: "Work spaces",
    design: "Design",
    build: "Build",
    responsive: "Responsive",
    request: "Customer request",
    form: "Form received",
    workflow: "Automation",
    logic: "Business rules",
    data: "Data stored",
    notification: "Notification",
    delivered: "Confirmation delivered",
    execution: "Request → connected workflow",
    input: "Customer signal",
    context: "Context",
    priority: "Priority",
    urgent: "Urgent support",
    account: "Existing customer",
    processing: "Matching signals",
    candidates: "Suggested routes",
    general: "General support",
    specialist: "Route to specialist",
    decision: "Recommended action",
    resolved: "Decision ready",
    platform: "Connected business platform",
    modules: "Independent modules",
    connected: "One connected system",
    crm: "Customer records",
    operations: "Operations",
    payments: "Payments",
    inventory: "Inventory",
    portal: "Customer portal",
    synced: "Shared data · synchronized",
    queued: "Queued",
    assigned: "Assigned",
    saved: "Saved",
    requestId: "Request #04",
    api: "Validate request",
    signal: "Signal extraction",
    rules: "Context + priority",
    notifyRole: "Email / message",
    available: "Available",
    syncedDevice: "Workspace synchronized",
  },
  ar: {
    demo: "تصور تفاعلي · بيانات تجريبية",
    live: "النظام جاهز",
    synchronized: "متزامن",
    morning: "صباح الخير",
    today: "عمليات اليوم",
    bookings: "الحجوزات",
    tasks: "المهام",
    requests: "الطلبات",
    booking: "حجز #04",
    assignment: "تأكيد التعيين",
    selected: "تم اختيار التعيين",
    confirmed: "تم تأكيد التعيين",
    home: "الرئيسية",
    profile: "حسابي",
    overview: "نظرة عامة",
    customers: "العملاء",
    workflows: "سير العمل",
    reports: "التقارير",
    search: "بحث في مساحة العمل",
    dashboard: "لوحة العمليات",
    active: "سير عمل نشط",
    open: "طلبات مفتوحة",
    completed: "مهام مكتملة",
    activity: "النشاط الأخير",
    review: "مراجعة الطلب",
    reviewed: "تم اعتماد الطلب",
    pending: "بانتظار المراجعة",
    done: "مكتمل",
    website: "استوديو / مساحات",
    spaces: "مساحات لحياة أجمل.",
    websiteText: "مساحات مدروسة. تفاصيل متقنة. صُممت للحياة.",
    explore: "استكشف المساحات",
    collection: "المجموعة",
    living: "مساحات المعيشة",
    work: "مساحات العمل",
    design: "تصميم",
    build: "تطوير",
    responsive: "متجاوب",
    request: "طلب العميل",
    form: "استلام النموذج",
    workflow: "الأتمتة",
    logic: "قواعد العمل",
    data: "حفظ البيانات",
    notification: "إشعار",
    delivered: "تم إرسال التأكيد",
    execution: "طلب ← سير عمل متصل",
    input: "إشارة العميل",
    context: "السياق",
    priority: "الأولوية",
    urgent: "دعم عاجل",
    account: "عميل حالي",
    processing: "مطابقة الإشارات",
    candidates: "مسارات مقترحة",
    general: "الدعم العام",
    specialist: "التوجيه إلى متخصص",
    decision: "الإجراء المقترح",
    resolved: "القرار جاهز",
    platform: "منصة أعمال متكاملة",
    modules: "وحدات مستقلة",
    connected: "نظام واحد متصل",
    crm: "سجلات العملاء",
    operations: "العمليات",
    payments: "المدفوعات",
    inventory: "المخزون",
    portal: "بوابة العملاء",
    synced: "بيانات مشتركة · متزامنة",
    queued: "في الانتظار",
    assigned: "تم التعيين",
    saved: "محفوظ",
    requestId: "طلب #04",
    api: "التحقق من الطلب",
    signal: "استخراج الإشارات",
    rules: "السياق + الأولوية",
    notifyRole: "بريد / رسالة",
    available: "متاح",
    syncedDevice: "تمت مزامنة مساحة العمل",
  },
};
export type SceneCopy = typeof sceneCopy.en;
