create extension if not exists pgcrypto;

create type public.content_status as enum ('draft','published','archived');
create type public.app_role as enum ('admin','editor');
create type public.inquiry_status as enum ('new','reviewing','qualified','closed','spam');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_roles (user_id uuid not null references public.profiles(id) on delete cascade, role public.app_role not null, created_at timestamptz not null default now(), primary key(user_id,role));
create table public.media (id uuid primary key default gen_random_uuid(), storage_path text not null unique, mime_type text not null, byte_size bigint not null check(byte_size>0), width integer, height integer, alt_en text, alt_ar text, status public.content_status not null default 'draft', created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.services (id uuid primary key default gen_random_uuid(), slug text not null unique, title_en text not null, title_ar text not null, summary_en text not null, summary_ar text not null, outcome_en text, outcome_ar text, body_en text, body_ar text, status public.content_status not null default 'draft', sort_order integer not null default 0, published_at timestamptz, created_by uuid references auth.users(id), updated_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.technologies (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, category text not null, status public.content_status not null default 'draft', sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.projects (id uuid primary key default gen_random_uuid(), slug text not null unique, title_en text not null, title_ar text not null, summary_en text not null, summary_ar text not null, industry_en text, industry_ar text, outcome_en text, outcome_ar text, year text, status public.content_status not null default 'draft', featured boolean not null default false, is_demo boolean not null default false, cover_media_id uuid references public.media(id) on delete set null, sort_order integer not null default 0, published_at timestamptz, created_by uuid references auth.users(id), updated_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.case_studies (id uuid primary key default gen_random_uuid(), project_id uuid not null unique references public.projects(id) on delete cascade, overview_en text, overview_ar text, challenge_en text, challenge_ar text, objectives_en text, objectives_ar text, solution_en text, solution_ar text, security_en text, security_ar text, status public.content_status not null default 'draft', demo_enabled boolean not null default false, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.project_media (project_id uuid not null references public.projects(id) on delete cascade, media_id uuid not null references public.media(id) on delete cascade, role text not null check(role in ('cover','hero','gallery','diagram')), caption_en text, caption_ar text, sort_order integer not null default 0, primary key(project_id,media_id));
create table public.project_technologies (project_id uuid not null references public.projects(id) on delete cascade, technology_id uuid not null references public.technologies(id) on delete restrict, sort_order integer not null default 0, primary key(project_id,technology_id));
create table public.project_results (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, label_en text not null, label_ar text not null, value text, context_en text, context_ar text, verified boolean not null default false, source_note text, sort_order integer not null default 0, created_at timestamptz not null default now());
create table public.customer_journey_steps (id uuid primary key default gen_random_uuid(), case_study_id uuid not null references public.case_studies(id) on delete cascade, title_en text not null, title_ar text not null, description_en text, description_ar text, step_type text not null default 'action', sort_order integer not null, unique(case_study_id,sort_order));
create table public.architecture_nodes (id uuid primary key default gen_random_uuid(), case_study_id uuid not null references public.case_studies(id) on delete cascade, node_key text not null, label_en text not null, label_ar text not null, description_en text, description_ar text, node_type text not null check(node_type in ('channel','integration','automation','logic','service','output','custom')), layer integer not null check(layer>=0), sort_order integer not null default 0, unique(case_study_id,node_key));
create table public.architecture_connections (id uuid primary key default gen_random_uuid(), case_study_id uuid not null references public.case_studies(id) on delete cascade, source_node_id uuid not null references public.architecture_nodes(id) on delete cascade, target_node_id uuid not null references public.architecture_nodes(id) on delete cascade, connection_type text not null default 'data', label_en text, label_ar text, sort_order integer not null default 0, check(source_node_id<>target_node_id));
create table public.testimonials (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id) on delete set null, client_name text not null, role text, organization text, quote_en text not null, quote_ar text, media_id uuid references public.media(id) on delete set null, approved boolean not null default false, status public.content_status not null default 'draft', published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.insights (id uuid primary key default gen_random_uuid(), slug text not null unique, title_en text not null, title_ar text not null, excerpt_en text not null, excerpt_ar text not null, content_en text not null, content_ar text not null, category text not null, cover_media_id uuid references public.media(id) on delete set null, status public.content_status not null default 'draft', published_at timestamptz, created_by uuid references auth.users(id), updated_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.inquiries (id uuid primary key default gen_random_uuid(), name text not null, company text, email text not null, phone text, country text, service text not null, budget_range text, timeline text, description text not null, locale text not null default 'en' check(locale in ('en','ar')), status public.inquiry_status not null default 'new', consent_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.site_settings (key text primary key, value_en text, value_ar text, public boolean not null default false, updated_by uuid references auth.users(id), updated_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references auth.users(id) on delete set null, action text not null, resource text not null, resource_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index projects_public_idx on public.projects(status,published_at desc) where status='published';
create index services_public_idx on public.services(status,sort_order) where status='published';
create index insights_public_idx on public.insights(status,published_at desc) where status='published';
create index inquiries_status_idx on public.inquiries(status,created_at desc);
create index architecture_nodes_case_idx on public.architecture_nodes(case_study_id,layer,sort_order);
create index architecture_connections_case_idx on public.architecture_connections(case_study_id,sort_order);
create index audit_actor_idx on public.audit_logs(actor_id,created_at desc);

create or replace function public.has_role(required_role public.app_role) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from public.user_roles ur join public.profiles p on p.id=ur.user_id where ur.user_id=auth.uid() and ur.role=required_role and p.active); $$;
create or replace function public.can_edit_content() returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select public.has_role('admin') or public.has_role('editor'); $$;
revoke all on function public.has_role(public.app_role) from public; grant execute on function public.has_role(public.app_role) to authenticated;
revoke all on function public.can_edit_content() from public; grant execute on function public.can_edit_content() to authenticated;

alter table public.profiles enable row level security; alter table public.user_roles enable row level security; alter table public.media enable row level security; alter table public.services enable row level security; alter table public.technologies enable row level security; alter table public.projects enable row level security; alter table public.case_studies enable row level security; alter table public.project_media enable row level security; alter table public.project_technologies enable row level security; alter table public.project_results enable row level security; alter table public.customer_journey_steps enable row level security; alter table public.architecture_nodes enable row level security; alter table public.architecture_connections enable row level security; alter table public.testimonials enable row level security; alter table public.insights enable row level security; alter table public.inquiries enable row level security; alter table public.site_settings enable row level security; alter table public.audit_logs enable row level security;

create policy "public published services" on public.services for select using(status='published');
create policy "public published technologies" on public.technologies for select using(status='published');
create policy "public published projects" on public.projects for select using(status='published');
create policy "public published case studies" on public.case_studies for select using(status='published' and exists(select 1 from public.projects p where p.id=project_id and p.status='published'));
create policy "public project media" on public.project_media for select using(exists(select 1 from public.projects p where p.id=project_id and p.status='published'));
create policy "public project technologies" on public.project_technologies for select using(exists(select 1 from public.projects p where p.id=project_id and p.status='published'));
create policy "public verified results" on public.project_results for select using(verified and exists(select 1 from public.projects p where p.id=project_id and p.status='published'));
create policy "public journey" on public.customer_journey_steps for select using(exists(select 1 from public.case_studies c join public.projects p on p.id=c.project_id where c.id=case_study_id and c.status='published' and p.status='published'));
create policy "public architecture nodes" on public.architecture_nodes for select using(exists(select 1 from public.case_studies c join public.projects p on p.id=c.project_id where c.id=case_study_id and c.status='published' and p.status='published'));
create policy "public architecture connections" on public.architecture_connections for select using(exists(select 1 from public.case_studies c join public.projects p on p.id=c.project_id where c.id=case_study_id and c.status='published' and p.status='published'));
create policy "public approved testimonials" on public.testimonials for select using(status='published' and approved);
create policy "public published insights" on public.insights for select using(status='published');
create policy "public media" on public.media for select using(status='published');
create policy "public settings" on public.site_settings for select using(public=true);

create policy "own profile" on public.profiles for select to authenticated using(id=auth.uid() or public.has_role('admin'));
create policy "admins roles" on public.user_roles for all to authenticated using(public.has_role('admin')) with check(public.has_role('admin'));
create policy "editors manage media" on public.media for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage services" on public.services for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage technologies" on public.technologies for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage projects" on public.projects for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage case studies" on public.case_studies for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage project media" on public.project_media for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage project technologies" on public.project_technologies for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage results" on public.project_results for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage journeys" on public.customer_journey_steps for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage nodes" on public.architecture_nodes for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage connections" on public.architecture_connections for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage testimonials" on public.testimonials for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors manage insights" on public.insights for all to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "editors view inquiries" on public.inquiries for select to authenticated using(public.can_edit_content());
create policy "editors update inquiries" on public.inquiries for update to authenticated using(public.can_edit_content()) with check(public.can_edit_content());
create policy "admins settings" on public.site_settings for all to authenticated using(public.has_role('admin')) with check(public.has_role('admin'));
create policy "admins audit logs" on public.audit_logs for select to authenticated using(public.has_role('admin'));

